<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function ses_current_posts_help($path, $arg) {
  switch ($path) {
    case "admin/help#ses_current_posts":
      return t("Displays links to nodes created on this date");

      break;
  }
}

/**
 * Implements hook_block_info().
 */
function ses_current_posts_block_info() {
  $blocks['ses_current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('SES Current Posts'),
    // Default Settings.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Custom content function.
 *
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 *
 * @return
 *   A result set of the targeted posts.
 */
function ses_current_posts_contents($display) {
  // Get today's date.
  $today = getdate();
  // Calculate the date a week ago.
  $start_time = mktime(0, 0, 0, $today['mon'], ($today['mday'] - 7), $today['year']);
  // Get all posts from one week ago to the present.
  $end_time = time();

  // NEW LINE.
  $max_num = variable_get('ses_current_posts_max', 3);

  // Use Database API to retrieve current posts.
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1)
    ->condition('created', array($start_time, $end_time), 'BETWEEN')
    ->orderBy('created', 'DESC');

  if ($display == 'block') {
    // Restrict the range if called with 'block' argument.
    $query->range(0, $max_num);
  } // Now proceeds to execute().
  // If called by page, query proceeds directly to execute().

  return $query->execute();
}

/**
 * Implements hook_block_view().
 */
function ses_current_posts_block_view($delta = '') {
  switch ($delta) {
    case 'ses_current_posts':
      if (user_access('access content')) {
        // Retrieve and process data here.
        // Use our custom function to retrieve data.
        $result = ses_current_posts_contents('block');
        // Array to contain items for the block to render.
        $items = array();
        // Iterate over the resultset and format as links.
        foreach ($result as $node) {
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          );
        }
        // No content in the last week.
        if (empty($items)) {
          $block['content'] = t('No posts available');
        }
        else {
          // Pass data through theme function.
          $block['content'] = theme('item_list', array('items' => $items));
        }
      }

      return $block;
  }
}

/**
 * Implements hook_menu().
 */
function ses_current_posts_menu() {
  $items = array();

  $items['admin/config/content/ses_current_posts'] = array(
    'title' => 'SES Current posts',
    'description' => 'Configuration for Current posts module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ses_current_posts_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['ses_current_posts'] = array(
    'title' => 'SES Current posts',
    'page callback' => '_ses_current_posts_page',
    'access arguments' => array('access ses_current_posts content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback:  SES Current posts settings.
 *
 * @see ses_current_posts_menu()
 */
function ses_current_posts_form($form, &$form_state) {
  $form['ses_current_posts_max'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of posts'),
    '#default_value' => variable_get('ses_current_posts_max', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('The maximum number of links to display in the block.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements validation from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state during the processing
 */
function ses_current_posts_form_validate($form, &$form_state) {
  $max_num = $form_state['values']['ses_current_posts_max'];
  if (!is_numeric($max_num)) {
    form_set_error('ses_current_posts_max', t('You must enter a number for the maximum number of posts to display.'));
  }
  elseif ($max_num <= 0) {
    form_set_error('ses_current_posts_max', t('Maximum number of posts to display must be positive.'));
  }
}

/**
 * Implements hook_permission().
 */
function _ses_current_posts_permission() {
  return array(
    'access ses_currents_posts content' => array(
      'title' => t('Access Content for the SES current posts module')
    )
  );
}

/**
 * Custom page callback function, declared in current_posts_menu().
 */
function _ses_current_posts_page() {
  $result = ses_current_posts_contents('block');
  // Array to cantain items for the page to render.
  $items = array();
  // Iterate over the resultset and format as links.
  foreach ($result as $node) {
    $items[] = array(
      'data' => l($node->title, 'node/' . $node->nid),
    );
  }

  // No content in the last week.
  if (empty($items)) {
    $page_array['ses_current_posts_arguments'] = array(
      // Title serves as page subtitle.
      '#title' => t('All posts form the last week'),
      '#markup' => t('No posts available'),
    );
    return $page_array;
  }
  else {
    $page_array['ses_current_posts_arguments'] = array(
      '#title' => t('All posts form the last week'),
      '#items' => $items,
      // Theme hook with suggestion.
      '#theme' => 'item_list__ses_current_posts',
    );
    return $page_array;
  }
}
